import type { CSSProperties } from 'react'

/** Shared visual language for the standalone auth routes. */
export const authStyles: Record<string, CSSProperties> = {
  center: {
    minHeight: '100dvh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#08080a',
    padding: 16,
    fontFamily:
      'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
  },
  card: {
    background: '#101014',
    color: '#f4f4f5',
    border: '1px solid #26262c',
    borderRadius: 14,
    padding: 24,
    width: 'min(400px, 100%)',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  logo: { fontSize: 12, letterSpacing: 2, color: '#9b9ba4', fontWeight: 700 },
  title: { margin: 0, fontSize: 20 },
  muted: { margin: 0, color: '#9b9ba4', fontSize: 13, lineHeight: 1.6 },
  fine: { margin: 0, color: '#71717a', fontSize: 11, lineHeight: 1.6 },
  input: {
    background: '#17171c',
    border: '1px solid #2c2c33',
    borderRadius: 8,
    color: '#f4f4f5',
    padding: '11px 12px',
    fontSize: 14,
    width: '100%',
    boxSizing: 'border-box',
  },
  primary: {
    background: '#f4f4f5',
    color: '#101014',
    border: 'none',
    borderRadius: 8,
    padding: '11px 14px',
    fontWeight: 600,
    fontSize: 14,
    cursor: 'pointer',
  },
  primaryLink: {
    background: '#f4f4f5',
    color: '#101014',
    border: 'none',
    borderRadius: 8,
    padding: '11px 14px',
    fontWeight: 600,
    fontSize: 14,
    textAlign: 'center',
    textDecoration: 'none',
    display: 'block',
  },
  link: {
    background: 'transparent',
    border: 'none',
    color: '#9b9ba4',
    fontSize: 13,
    cursor: 'pointer',
    textDecoration: 'underline',
    padding: 0,
    textAlign: 'center',
  },
  error: { color: '#f87171', fontSize: 12, margin: 0 },
  notice: { color: '#4ade80', fontSize: 12, margin: 0 },
}
